apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "codeok.fullname" . }}
  labels:
    {{- include "codeok.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "codeok.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "codeok.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "codeok.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.app.port }}
              protocol: TCP
          env:
            # Application configuration
            - name: HOST
              value: "0.0.0.0"
            - name: PORT
              value: "{{ .Values.app.port }}"
            - name: TARGET_USERNAME
              value: "{{ .Values.app.targetUsername }}"
            
            # GitHub App secrets from Kubernetes secret
            - name: GITHUB_APP_ID
              valueFrom:
                secretKeyRef:
                  name: {{ include "codeok.fullname" . }}-secrets
                  key: github-app-id
            - name: GITHUB_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "codeok.fullname" . }}-secrets
                  key: github-private-key
            {{- if .Values.secrets.github.installationId }}
            - name: GITHUB_INSTALLATION_ID
              valueFrom:
                secretKeyRef:
                  name: {{ include "codeok.fullname" . }}-secrets
                  key: github-installation-id
            {{- end }}
            
            # Webhook secret
            - name: WEBHOOK_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "codeok.fullname" . }}-secrets
                  key: webhook-secret
          
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          
          # Volume mounts for temporary files (since we use read-only root filesystem)
          volumeMounts:
            - name: tmp
              mountPath: /tmp
            - name: app-tmp
              mountPath: /app/tmp
            {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
      
      volumes:
        # Temporary volumes for read-only root filesystem
        - name: tmp
          emptyDir: {}
        - name: app-tmp
          emptyDir: {}
        {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }} 