# Example secrets configuration for development
# DO NOT commit this file with real secrets!
# Copy this file and fill in your actual values

# For development/testing - use direct secrets
secrets:
  github:
    appId: "1530517"  # Your GitHub App ID
    privateKey: |
      -----BEGIN RSA PRIVATE KEY-----
      YOUR_PRIVATE_KEY_CONTENT_HERE
      -----END RSA PRIVATE KEY-----
    installationId: ""  # Optional - will be determined automatically
  webhook:
    secret: "your-webhook-secret-here"

# For production - use External Secrets with AWS Secrets Manager
externalSecrets:
  enabled: false  # Set to true for production
  secretStore:
    name: "aws-secretsmanager-store"
    kind: "SecretStore"
  awsSecrets:
    region: "us-west-2"
    githubAppId:
      name: "prod/codeok/github-app-id"
      key: "app-id"
    githubPrivateKey:
      name: "prod/codeok/github-private-key"
      key: "private-key"
    webhookSecret:
      name: "prod/codeok/webhook-secret"
      key: "secret" 