# Default values for codeok
# This is a YAML-formatted file.

replicaCount: 1

image:
  repository: jesuspaz/codeok
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

# Application configuration
app:
  port: 8000
  # Target username for PR auto-approval
  targetUsername: "codeok"

# Secrets configuration - these will be created as Kubernetes secrets
secrets:
  # GitHub App configuration
  github:
    # App ID (number) - required
    appId: ""
    # Private key content or path to mounted secret
    privateKey: ""
    # Optional: Installation ID
    installationId: ""
  
  # Webhook secret for signature verification
  webhook:
    secret: ""

# External secrets configuration (recommended for production)
externalSecrets:
  enabled: false
  # If using External Secrets Operator
  secretStore:
    name: "aws-secretsmanager"
    kind: "SecretStore"
  # AWS Secrets Manager configuration
  awsSecrets:
    region: "us-west-2"
    githubAppId:
      name: "codeok/github-app-id"
      key: "app-id"
    githubPrivateKey:
      name: "codeok/github-private-key"
      key: "private-key"
    webhookSecret:
      name: "codeok/webhook-secret"
      key: "secret"

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Automatically mount a ServiceAccount's API credentials?
  automount: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext:
  fsGroup: 1000
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

service:
  type: ClusterIP
  port: 80
  targetPort: 8000

# AWS Load Balancer Controller configuration
ingress:
  enabled: true
  className: "alb"
    
  hosts:
    - host: webhook.your-domain.com
      paths:
        - path: /
          pathType: Prefix

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

livenessProbe:
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 5
  periodSeconds: 5
  timeoutSeconds: 3
  failureThreshold: 3

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

# Additional volumes and volume mounts
volumes: []
volumeMounts: []

nodeSelector: {}

tolerations: []

affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 100
      podAffinityTerm:
        labelSelector:
          matchExpressions:
          - key: app.kubernetes.io/name
            operator: In
            values:
            - codeok
        topologyKey: kubernetes.io/hostname

# Network policies for enhanced security
networkPolicy:
  enabled: true
  ingress:
    - from:
      - namespaceSelector:
          matchLabels:
            name: ingress-nginx
      ports:
      - protocol: TCP
        port: 8000
  egress:
    # Allow DNS
    - to: []
      ports:
      - protocol: UDP
        port: 53
    # Allow HTTPS to GitHub API
    - to: []
      ports:
      - protocol: TCP
        port: 443

# Pod Disruption Budget
podDisruptionBudget:
  enabled: true
  minAvailable: 1 