{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "codeok.fullname" . }}-external-secrets
  labels:
    {{- include "codeok.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStore.name }}
    kind: {{ .Values.externalSecrets.secretStore.kind }}
  target:
    name: {{ include "codeok.fullname" . }}-secrets
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        github-app-id: "{{ `{{ .githubAppId }}` }}"
        github-private-key: "{{ `{{ .githubPrivateKey }}` }}"
        webhook-secret: "{{ `{{ .webhookSecret }}` }}"
  data:
  - secretKey: githubAppId
    remoteRef:
      key: {{ .Values.externalSecrets.awsSecrets.githubAppId.name }}
      property: {{ .Values.externalSecrets.awsSecrets.githubAppId.key }}
  - secretKey: githubPrivateKey
    remoteRef:
      key: {{ .Values.externalSecrets.awsSecrets.githubPrivateKey.name }}
      property: {{ .Values.externalSecrets.awsSecrets.githubPrivateKey.key }}
  - secretKey: webhookSecret
    remoteRef:
      key: {{ .Values.externalSecrets.awsSecrets.webhookSecret.name }}
      property: {{ .Values.externalSecrets.awsSecrets.webhookSecret.key }}
{{- end }} 