{{- if not .Values.externalSecrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "codeok.fullname" . }}-secrets
  labels:
    {{- include "codeok.labels" . | nindent 4 }}
type: Opaque
data:
  # GitHub App configuration
  github-app-id: {{ .Values.secrets.github.appId | b64enc | quote }}
  github-private-key: {{ .Values.secrets.github.privateKey | b64enc | quote }}
  {{- if .Values.secrets.github.installationId }}
  github-installation-id: {{ .Values.secrets.github.installationId | b64enc | quote }}
  {{- end }}
  
  # Webhook secret
  webhook-secret: {{ .Values.secrets.webhook.secret | b64enc | quote }}
{{- end }} 